<?php

/**
 * @file
 * Axelerant Custom module file.
 */

/**
 * Implements hook_menu().
 */
function axelerant_custom_menu() {
  // Menu for json representation of node.
  $items['page_json/FOOBAR12345/%'] = array(
    'title' => 'Json Representation of node',
    'description' => 'A page which displays the json representation of node',
    'page callback' => 'axelerant_custom_node_json_output',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/axelerant_custom.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_variable_info().
 */
function axelerant_custom_variable_info($options) {
  // Define variable site_api_key.
  $variables['site_api_key'] = array(
    'title' => t('Site API Key', array(), $options),
    'description' => t('Site API Key', array(), $options),
    'type' => 'text',
    // Set an administer permission.
    'access' => 'administer menus',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function axelerant_custom_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  // Add field site api key.
  $form['site_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => variable_get('site_api_key', t('No API Key yet')),
  );
  // Add a custom submit callback.
  // Make sure that our submit callback is executed first.
  array_unshift($form['#submit'], 'axelerant_custom_system_site_information_settings_submit');
  // Update the label of submit button.
  $form['actions']['submit']['#value'] = t('Update Configurations');
}

/**
 * Custom submit callback for system_site_information_settings_form.
 */
function axelerant_custom_system_site_information_settings_submit(&$form, &$form_state) {
  // Get the previous value of site_api_key.
  $site_api_key = variable_get('site_api_key');
  if (isset($form_state['values']['site_api_key'])) {
    $new_site_api_key = $form_state['values']['site_api_key'];
    // Proceed only if the old site api key is different from new one.
    if ($site_api_key != $new_site_api_key) {
      variable_set('site_api_key', $new_site_api_key);
      drupal_set_message(t('The site api key has been updated with value @key',
        array('@key' => $new_site_api_key)), 'status'
      );
    }
  }
}
